# 服务配置
server:
  port: 20 # 启动端口


spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.25.196.200:3306/Kying_debug?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&autoReconnect=true
    username: root
    password: studyhard!
  # 热部署
  devtools:
    restart:
      enabled: true

# 日志打印配置
logging:
  level:
    com.baomidou.mybatisplus.samples: debug

# Mybatis-Plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml

wxconfig:
  appid: wx423d4cbbe814ed74

wx:
  miniapp:
    configs:
      - appid: 123 #微信小程序的appid
        secret: #微信小程序的Secret
        #token: #微信小程序消息服务器配置的token
        # aesKey: #微信小程序消息服务器配置的EncodingAESKey
        msgDataFormat: JSON


