import search from './search.png'
import searchIcon from './searchIcon.png'
import address from './address.png'
import edit from './edit.png'
import edit2 from './edit2.png'
import edit3 from './edit3.png'
import outlined from './outlined.png'
import add from './add.png'
import addIcon from './addIcon.png'
import collect from './collect.png'
import collectDone from './collectDone.png'
import outline_gray from './outline_gray.png'
import agreed from './agreed.png'
import onAgreed from './onAgreed.png'
import close from './close.png'
import file1 from './file1.png'
import file2 from './file2.png'
import file3 from './file3.png'
import choice from './choice.png'
import onChoice from './onChoice.png'
import check from './check.png'
import chat from './chat.png'
import deleteIcon from './deleteIcon.png'
import selectDown from './selectDown.png'
import train from './train.png'
import coach from './coach.png'

const icon = { search, searchIcon, address, edit, outlined, add, collect, collectDone, outline_gray, agreed, onAgreed, edit2, edit3, close, file1, file2, file3, choice, onChoice, check, chat, deleteIcon, addIcon, selectDown, train, coach }

export default icon